version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
    ports:
      - 5432:5432
    expose:
      - 5432          
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: dev
    ports:
      - "8085:8085"
    restart: unless-stopped
    depends_on:
      - postgres